load("@rules_java//java:defs.bzl", "java_test")

java_test(
    name = "CellTest",
    srcs = ["CellTest.java"],
    test_class = "unsw.dungeon.gameplay.CellTest",
    deps = [
        "//src/unsw/dungeon",
        "//lib:junit.jar",
    ],
)

java_test(
    name = "MapObjectStateTest",
    srcs = ["MapObjectStateTest.java"],
    test_class = "unsw.dungeon.gameplay.MapObjectStateTest",
    deps = [
        "//src/unsw/dungeon",
        "//lib:junit.jar",
    ],
)

java_test(
    name = "PlayerEnemyCollisionTest",
    srcs = ["PlayerEnemyCollisionTest.java"],
    test_class = "unsw.dungeon.gameplay.PlayerEnemyCollisionTest",
    deps = [
        "//src/unsw/dungeon",
        "//lib:junit.jar",
    ],
)

java_test(
    name = "DoorTest",
    srcs = ["DoorTest.java"],
    test_class = "unsw.dungeon.gameplay.DoorTest",
    deps = [
        "//src/unsw/dungeon",
        "//lib:junit.jar",
    ],
)

java_test(
    name = "BoulderMoveTest",
    srcs = ["BoulderMoveTest.java"],
    test_class = "unsw.dungeon.gameplay.BoulderMoveTest",
    deps = [
        "//src/unsw/dungeon",
        "//lib:junit.jar",
    ],
)

java_test(
    name = "FloorSwitchTest",
    srcs = ["FloorSwitchTest.java"],
    test_class = "unsw.dungeon.gameplay.FloorSwitchTest",
    deps = [
        "//src/unsw/dungeon",
        "//lib:junit.jar",
    ],
)

java_test(
    name = "PortalTest",
    srcs = ["PortalTest.java"],
    test_class = "unsw.dungeon.gameplay.PortalTest",
    deps = [
        "//src/unsw/dungeon",
        "//lib:junit.jar",
    ],
)

java_test(
    name = "CollectiblesAddedToInventoryTest",
    srcs = ["CollectiblesAddedToInventoryTest.java"],
    test_class = "unsw.dungeon.gameplay.CollectiblesAddedToInventoryTest",
    deps = [
        "//src/unsw/dungeon",
        "//lib:junit.jar",
    ],
)

java_test(
    name = "PotionTimerTest",
    srcs = ["PotionTimerTest.java"],
    test_class = "unsw.dungeon.gameplay.PotionTimerTest",
    deps = [
        "//src/unsw/dungeon",
        "//lib:junit.jar",
    ],
)

java_test(
    name = "WallTest",
    srcs = ["WallTest.java"],
    test_class = "unsw.dungeon.gameplay.WallTest",
    deps = [
        "//src/unsw/dungeon",
        "//lib:junit.jar",
    ],
)

java_test(
    name = "WinningConditionTest",
    srcs = ["WinningConditionTest.java"],
    test_class = "unsw.dungeon.gameplay.WinningConditionTest",
    deps = [
        "//src/unsw/dungeon",
        "//lib:junit.jar",
    ],
)