load("@rules_java//java:defs.bzl", "java_test")

java_test(
    name = "CellTest",
    srcs = ["CellTest.java"],
    test_class = "unsw.dungeon.gameplay.CellTest",
    deps = [
        "//src/unsw/dungeon",
        "//lib:junit.jar",
    ],
)
