load("@rules_java//java:defs.bzl", "java_test")

java_test(
    name = "BasicTest",
    srcs = ["BasicTest.java"],
    test_class = "unsw.dungeon.BasicTest",
    deps = [
        "//lib:junit.jar",
    ],
)
